const express = require('express');
const router = express.Router();
const { protect, adminOnly } = require('../middleware/authMiddleware');
const a = require('../controllers/adminController');
router.use(protect, adminOnly);
router.get('/fans', a.getAllFans);
router.patch('/fans/:id/deactivate', a.deactivateFan);
router.get('/teams', a.getTeams);
router.post('/teams', a.addTeam);
router.put('/teams/:id', a.updateTeam);
router.patch('/teams/:id/deactivate', a.deactivateTeam);
router.get('/players', a.getPlayers);
router.post('/players', a.addPlayer);
router.put('/players/:id', a.updatePlayer);
router.patch('/players/:id/transfer', a.transferPlayer);
router.post('/players/:id/awards', a.assignAward);
router.get('/stadiums/usage', a.getStadiumUsage);
router.get('/stadiums', a.getStadiums);
router.post('/stadiums', a.addStadium);
router.get('/matches', a.getMatches);
router.post('/matches', a.scheduleMatch);
router.patch('/matches/:id/finalize', a.finalizeMatch);
router.patch('/matches/:id/cancel', a.cancelMatch);
router.post('/matches/:id/sponsors', a.linkSponsor);
router.delete('/matches/:id/sponsors/:sponsorId', a.unlinkSponsor);
router.post('/performance', a.recordPerformance);
router.get('/performance/:matchId', a.getMatchPerformance);
router.get('/training', a.getTrainingSessions);
router.post('/training', a.createTraining);
router.patch('/training/:id/attendance', a.updateAttendance);
router.get('/staff', a.getStaff);
router.post('/staff', a.addStaff);
router.get('/supplies/low-stock', a.getLowStockSupplies);
router.get('/supplies', a.getSupplies);
router.post('/supplies', a.addSupply);
router.put('/supplies/:id', a.updateSupply);
router.get('/sponsors', a.getSponsors);
router.post('/sponsors', a.addSponsor);
router.get('/coaches', a.getCoaches);
router.post('/coaches', a.addCoach);
module.exports = router;
